apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ewdse7oy5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ewdse7oy5-java-quarkus-gitops